services:
  - type: web
    name: organika-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=. gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
