services:
  - type: web
    name: organika-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
