"""Add service_records table

Revision ID: 79a12e36672d
Revises: f2f1742f8cb4
Create Date: 2025-07-10 13:35:25.394392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a12e36672d'
down_revision = 'f2f1742f8cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('position_title', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('office', sa.String(length=150), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('salary_monthly', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('separation_date', sa.Date(), nullable=True),
    sa.Column('separation_cause', sa.String(length=150), nullable=True),
    sa.Column('leave_without_pay', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['public.employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('plantilla_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('plantilla_items_employee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'], referent_schema='public', ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('plantilla_items_employee_id_fkey'), 'employees', ['employee_id'], ['id'], ondelete='SET NULL')

    op.drop_table('service_records', schema='public')
    # ### end Alembic commands ###
