"""Remove status column from plantilla_items

Revision ID: a9ecc62573ed
Revises: f1c7f763ac25
Create Date: 2025-07-09 11:03:40.605248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ecc62573ed'
down_revision = 'f1c7f763ac25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('plantilla_items_employee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'], referent_schema='public', ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('plantilla_items_employee_id_fkey'), 'employees', ['employee_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
