"""Update plantilla_items

Revision ID: f1c7f763ac25
Revises: 
Create Date: 2025-07-09 11:00:00.239908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c7f763ac25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_items', schema=None) as batch_op:
        batch_op.alter_column('annual_salary_actual',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_employee'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'], referent_schema='public', ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_employee'), 'employees', ['employee_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('annual_salary_actual',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)

    # ### end Alembic commands ###
