"""Updated employee model with DOB, status, promotion date

Revision ID: f2f1742f8cb4
Revises: 5f67926226c0
Create Date: 2025-07-09 14:21:17.916274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f1742f8cb4'
down_revision = '5f67926226c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('employment_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('plantilla_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('plantilla_items_employee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'], referent_schema='public', ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('plantilla_items_employee_id_fkey'), 'employees', ['employee_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('employment_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
